FROM nginx:1.25.5-alpine

RUN apk add --no-cache curl dos2unix

COPY nginx_conf_template.railway /etc/nginx/conf.d/nginx.conf.template.railway
COPY mcp_conf_inc.template /etc/nginx/conf.d/mcp.conf.inc.template
COPY mcp_upstream_conf_inc.template /etc/nginx/conf.d/mcp_upstream.conf.inc.template
COPY run-nginx.railway.sh /run-nginx.railway.sh

RUN dos2unix /run-nginx.railway.sh && chmod +x /run-nginx.railway.sh

EXPOSE 80

ENTRYPOINT ["/run-nginx.railway.sh"]